---
  - name: Copy hadoop tar from s3 bucket to hadoop-cluster
    aws_s3:
      s3_url: "{{ s3_url }}"
      bucket: "{{ s3_bucket_name }}"
      object: "/{{ hadoop_source }}"
      dest: "{{ home_path }}/{{ hadoop_source }}"
      mode: get
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    when: "'Hadoop-cluster' in group_names"  
    

  - name: Unzip the hadoop Cluster
    ansible.builtin.unarchive:
      src: "{{ hadoop_source }}"
      dest: "{{ home_path }}"    
      remote_src: yes  
    when: "'Hadoop-cluster' in group_names"   
