---
  - name: Copy spark tar from s3 bucket to primary
    aws_s3:
      s3_url: "{{ s3_url }}"
      bucket: "{{ s3_bucket_name }}"
      object: "{{ spark_source }}"
      dest: "{{ home_path }}/{{ spark_source }}"
      mode: get
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"          
    when: inventory_hostname in groups['Spark']

  - name: Unzip spark
    ansible.builtin.unarchive:
      src: "{{ spark_source }}"
      dest: "{{ home_path }}"     
      remote_src: yes 
    when: inventory_hostname in groups['Spark']