---
  - name: Copy zookeeper tar from s3 bucket to all nodes
    aws_s3:
      s3_url: "{{ s3_url }}"
      bucket: "{{ s3_bucket_name }}"
      object: "{{ zookeeper_source }}"
      dest: "{{ home_path }}/{{ zookeeper_source }}"
      mode: get  
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    when: "'Zookeeper-cluster' in group_names"

  - name: Unzip the zookeeper Cluster
    ansible.builtin.unarchive:
      src: "{{ zookeeper_source }}"
      dest: "{{ home_path }}" 
      remote_src: yes
    when: "'Zookeeper-cluster' in group_names"     