---
  - name: Copy hbase tar from s3 bucket 
    aws_s3:
      s3_url: "{{ s3_url }}"
      bucket: "{{ s3_bucket_name }}"
      object: "{{ hbase_source }}"
      dest: "{{ home_path }}/{{ hbase_source }}"
      mode: get
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    when: "'Hbase-cluster' in group_names"

  - name: Unzip hbase
    ansible.builtin.unarchive:
      src: "{{ hbase_source }}"
      dest: "{{ home_path }}"     
      remote_src: yes 
    when: "'Hbase-cluster' in group_names"