---
  - name: Copy presto tar from s3 bucket on master and slave
    aws_s3:
      s3_url: "{{ s3_url }}"       
      bucket: "{{ s3_bucket_name }}"
      object: "{{ presto_source }}"
      dest: "{{ home_path }}/{{ presto_source }}"
      mode: get
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"          
    when: "'Presto-cluster' in group_names"

  - name: Unzip presto on master and slave
    ansible.builtin.unarchive:
      src: "{{ presto_source }}"
      dest: "{{ home_path }}"
      remote_src: yes
    when: "'Presto-cluster' in group_names"