---
all:
  vars:
    ansible_connection: ssh
    ansible_port: 22
    ansible_user: nhadmin
    ansible_password: August@2023
  children:
    Hadoop-cluster:
      children:
        namenodes:
          hosts:
            100.26.10.168:
            100.26.10.169:
        datanodes:
          hosts:
            100.26.10.170:
            100.26.10.171:
            100.26.10.172:
        tasknodes:
          hosts:
            100.26.10.172:
    Hbase-cluster:  ## Same host count should be reflected in zookeeper group
      children:
        hmaster:
          hosts:
            100.26.1.169:
        hregion-server:
          hosts:
            100.26.10.170:
            100.26.10.171:
            100.26.10.172:
    Flink-cluster:  ## Same host count should be reflected in zookeeper group
      children:
        jobmanager:
          hosts:
            100.26.10.168:
        taskmanager:
          hosts:
            100.26.10.170:
            100.26.10.172:
    Hive:
      hosts:
        100.26.10.169:
    Zookeeper-cluster:
      hosts:
        100.26.10.169:
        100.26.10.170:
        100.26.10.171:
        100.26.10.172:
    Presto-cluster:
      children:
        presto-coordinator:
          hosts:
            100.26.10.168:
        presto-worker:
          hosts:
            100.26.10.170:
            100.26.10.171:
            100.26.10.172:
    Spark:
      hosts:
        100.26.10.168:
    Mysql:
      hosts:
        100.26.10.168: ## IF you change Ip change global variable also

