---
# Check Python version and install pip2
  - name: Install pip package for Python 2
    raw: curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | sudo python2 -
    when: "'2' in ansible_python_version"

# Install pip3 for Debian/Ubuntu systems (using apt)
  - name: Install python3-pip package for Debian/Ubuntu systems (using apt)
    apt:
      name: python3-pip
      state: present
    when:
      - ansible_distribution == 'Ubuntu'
      - "'3' in ansible_python_version"

# Install pip3 For Red Hat/CentOS systems (using yum)
  - name: Install python3-pip package for Red Hat/CentOS systems
    yum:
      name: python3-pip
      state: present
    when:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      - "'3' in ansible_python_version"

# Install boto3
  - name: Install boto3
    pip:
      name: boto3
      state: present